# permissions for end users to edit ravendbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ravendbcluster-editor-role
rules:
- apiGroups:
  - ravendb.ravendb.io
  resources:
  - ravendbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ravendb.ravendb.io
  resources:
  - ravendbclusters/status
  verbs:
  - get
