# permissions for end users to view ravendbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ravendb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ravendbcluster-viewer-role
rules:
- apiGroups:
  - ravendb.ravendb.io
  resources:
  - ravendbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ravendb.ravendb.io
  resources:
  - ravendbclusters/status
  verbs:
  - get
